const introductionScene = `Rain lashes against the worn canvas of the tent. A solitary lantern swings like a pendulum over the entrance, casting erratic shadows across the fabric, which seem to twist and writhe in throes of increasingly grotesque passion as you approach. You part the beaded curtains and step inside. Warmth and light engulf your senses, as if the storm outside has ceased to exist. The air is heavy with the musk of leather-bound books and stacks of old parchment; the sweet haze of blue smoke; the bundles of sage, cedar, lavender, and elderberries that have been bound and strung up around the room. Underneath, there is a sharp note of decay. “My царь!” Ludmilla crows, evidently delighted. She is sitting behind a table strewn with gleaming trinkets and ornate Spira cards, draped in graceful scarves of deep crimson and indigo. Her bracelets chime, softly, like church-bells, whenever she moves. Her eyes are amber-bright. “You’ve returned to me. I thought you might not, this round.” She takes a quick, business-like drag off her cigarette. “Very well. You still have a ways to go, first. And we should really perform the ritual beforehand. But I’m a soft touch for a lost cause.” She watches you sit down without blinking; her hair smells strongly of anise and cloves. “Let’s try this again, shall we?”`;
const introductionImage = "Entrance.jpg"

const scenePairs = [
    {
        escape: `“I sense carnage. I see—an operating theatre. Yes. When the Sun sleeps in the House of the Mountain, you will file into the operating theatre and take your seat. In the stands, you will look down at a man that you know well, flanked by two assistants in bloodstained lab coats. The human heart, Dr. Bellweather lectures, sings life through our veins, and helps us to bear the stress of blood’s demands. And yet! Like clockwork, how quickly—how predictably—it wears out over time. Between them, a terrified man, his flushed-drink face, his hideous lime-raw knuckles… Low, nervous voices. The rustle of bodies confined to narrow benches. Dr. Bellweather—handsome and formidable; formidably handsome, even—meets the eyes of the audience. Time me! He bellows. Next to you, the detective will take out a broken pocket-watch. And then Dr. Bellweather will raise his arm. And then he will bring down his arm. Blood breaks free of its bindings—a cool, gray day—a day like any other. Do you see that? The detective’s breath stings raw your earlobe. Does that look right to you? A man sawing into a delinquent leg. Or—there? In the thigh-meat—yes I do, yes I do see it!—a crown of brilliant red hair, wriggling, squirming, pushing, yearning for escape… Afterwards, you and the other students gather in the lab, your scalpels gripped tightly in your fists; that night, or another night, you will dream of arteries, a map unfolding, revealing countless paths worn down from use…”`,
        penance: `“I see… you, stumbling through the crooked halls of the Penrose Library for the Pursuit of the Invisible Sciences. I assume invisible, here, refers to the internal workings of the body? Your standard internal equipment; veins, arteries, lungs, fascia, aether, and so on? … I see. Where was I? Don’t tell me. Don’t tell me. Ah! There you are: right in my mind’s eye, which is sometimes recorded, in sacred texts, by learned men, as “the mind’s forge.” Books whisper your name as you pass. Their pages rustle, disturbed by strange hands. You descend into the archives, where bronze sconces secrete oily light on old papers, where corpse-stained fingers trace sprawling lines of incoherent cursive, in the hopes of deciphering the secret chronologies of circulation and anatomy. Patient histories, Dr. Holloway informs you, as you sign your name in his record-book, hold detailed accounts of previous injuries, treatments given, and outcomes witnessed. Each one tells a story of victory or loss, triumph or defeat. One file will fester in your mind, into the next day, and the next. 'Patient’s exact words: ‘There was a door in my eye. I closed it.’ Psychiatric evaluation deemed not only prudent, but critical...'”`,
        image: "Entrance.jpg"
    },
    {
        escape: `“Four of Serpilions. And reversed! This is not your night. No, no, all is not lost. The servitors can bring bittersweet memories or awkward interactions in crowded train-cars, nightmares or small-talk, existential crises or coerced agreements. It all depends. Now, where did I put my aconite blossoms? And that damned bowl of sanctified rain-water? … Stir with red salt… and wait for the petals to fade to silver. We call upon the younger sisters of Prince Mediateth, the Left-Hand, who disarticulated the fortieth veil at the behest of thirteen lost orphan-shepherds. Attend to our plea. Reflect your image within shifting waters… Do you hear that? Listen. How delightful! Like memories of childhood, the distant drumming of witch-wings scatters upon the wind. I see a mirror-vendor, hawking his wares in the shadow of an olive tree. Closer, he beckons you. Closer. Closer, still! Now, close your eyes. Now, open them. Instead of your own reflection, what will you see? Who will you see? There is a scar. There is an awareness of absence. She is unpredictable—adulterous, enigmatic. She copies your movements in an exaggerated, mocking manner. She will cover her missing eye, and the chaos in the marketplace will shatter the glass, and the vendor, an unsympathetic man, hardened by a lifetime in sales, will charge you eight dinara for emotional, physical, and philosophical damages…`, 
        penance: `“Four of Serpilions. The handmaidens, or Death’s sisters. They are associated with aconite, graveyards, drums, silver, and estuaries. They are the keepers of memory and the ensurers of vengeance. Terrible table-manners, the whole lot of them. Hand me that bowl. Watch how the petals bleed silver around their edges. One of many signets of the court of the domovoi. In the court, roses and thorns and spiders run rampant. You will try to approach this day as you would have before: star-gazing at night, attending and assisting with surgical operations in the morning.  A spectral form—a woman with a moth for a face—a row of shrieking, squirming crows on the lip of a turret. A plea for justice. You will follow a woman’s familiar voice down the winding passageways of memory, through abandoned, elaborate feast-halls, because her song reminds you of someone you used to love. When twilight falls, you will return home; you will barricade the doors of your flat, but Natalia will still emerge from the place behind the mirror, her skin as translucent as frost. Her intestines pulse and writhe in her glass-corpse like dark jewels, and she has artfully draped a string of black pearls around her waist. Three hundred and sixty-five of them, she will remark. (A bit cryptic, isn’t she? Not to my taste—but then, you men of science will have your fascinations…) One for each and every second you held captive my neck. You owe me that much, don\'t you: царь? Or shall I finally take my pound of flesh? Personally, I\'ve often wondered if the goals of the moths are intertwined with the quests of the sky-court—in other words, with consumption. It was, after all, the method early querents used to navigate the wounds in the skin of the world. But their visions were inaccurate and fleeting, until they learned how to see without sight. Take that as you will.“`,
        image: "Four of Serpilions.jpg"
    }, 
    {
        escape: `“You will embark upon a surreal collection of quests. No, rites. No! Rituals. There—can you see? Look closer. Closer. That’s it. Closer. You. Whispering obscenely false apologies into a crow’s jagged-open. You. Burying your tongue in the black dirt of an ancient crossroads beneath blue midnight. You. Bathing in a clawfoot bathtub filled with flaking bloodstains and vital black bile. You will tell yourself different stories with each new attempt, warm your palms by the [well-worn] hearth of self-dishonesty with every subsequent failure. Seven days—what? Yes. Yes, I said seven. Would you kindly—Erinyes. Erinyes. I’m not doing this with you right now. Where was I? Oh, yes. Another night, the same night—what does it matter?—you will hide your outer-self in radiant gold, an Aeolian lyre cradled like an infant in your arms, pearlescent strings stripped from the ligaments of wolf-guts. You will begin to play under the eavesdropping moon. A haunting tune will ripple outwards from your fingertips, enticing the wind to dance to the fervor of your lunatic beat. As the melody ascends, echoes of time dapple the air, light bleeding through the cracks. Alone, and not alone, you will chant under the waning crescent: as salt meets the earth, as the tower waves and recedes, as Morgen remains, eternal, anchored to coherence by chains unseen… but the climax of the composition—the heart of the ritual—will elude both you and your eager, invisible listener. A word of advice? The moths may offer escape, but they do not bow to the mind-in-despair, nor the conscience devoid of it. Take that as you will.”`, 
        penance: `“You will attend a seance at the Parlor of Echoes, an opulent sanctum of lingering spirits and grief, operated by a compellingly corpulent widow who calls herself Madame Solostris. Those desperate to make contact with the other side sometimes claim to hear her voice in fitful dreams. I’ve heard that she will wait at the foot of a bereaved lover’s bed and watch them sleep, incisors as sharp as a shrike’s talons; perhaps this is nothing more than catty talk between economic competitors. Violet clouds of smoke swirl in the air, heady with ginger and cardamom. Madame Solostris will only begin the ritual when the parlor-room positively hums with desolation. She also requires payment upfront, in deference of the river she will “profess to cross,” with you and eight other initiates. Warily, you proceed to clear the table and interwreathe together protective strands of salt and lavender. Solostris could navigate the abyss with a burnished locket, if she so chose; this time, she opts for a stronger instrument. And rightfully so! Many spirits will be drawn to your desperation: perhaps they can sense your stuttered heartbeat, skittering off the walls of your throat like a startled moth. When Madame Sosostris fails to control them, they will unleash flames upon your circle. Even in that smoky, crowded room, one presence stands out, choking your lungs with fleeting memories. Another entranced participant is chanting with fervent intensity, his eyes amber-bright. The betrayal. The passion. The despair. The betrayal. The ritual. The rebirth. The betrayal. The palace. The seven-fold, seven-limbed gate…”`,
        image: "Entrance.jpg"
    }, 
    {
        escape: `“The whispers in the woods. Jade-tinted canopies. A child’s eye, emboweled in obsidian depths… Natalia used to laugh at your cold-blooded, tight-lipped pragmatism. No good for a doctor, she would chide. You remind me of my first manager. So reticent! It was like sucking blood from a stone, getting him to reveal any sordid behavior from his previous lives. And all the girls loved it, of course. Restraint in a man can be so… tantalizing. Or was it his secrecy? He was never handsome, Mr. Hobson—big, chipmunk teeth; gaping, ghost-town eyes—but when he did speak, he wasted no words. Not like we do, on the trains, or in shops, or at boarding-houses. Meaningless conversations. Silly ceremonies! Here, she shrugged, or perhaps winced. His twin brother murdered him in a cafe in Kosovo in 1923. He raised turtledoves. A strange man. Still, he never stole from me or the other girls, which is more than I can say for my current employers. She plucked the lit cigarette from your fingers and brought it to her small, rose-petal lips with a precise flourish. You knew that she had practiced that gesture a thousand times, in a thousand mirrors, but it made no difference, did not change how strongly you felt when she winked at you, her face hidden behind a veil of blue, sweet-smelling smoke. Part of her was buried in a strange wood, long before flesh and spirit were divided. Sometimes, your memories lead you there—other nights, you spot a lonely wisp of a girl among the trees, or the sharper gleam of her vengeful ghost between their branches. Often, they will take the form of wandering children. Memories, that is. Not ghosts. Did you think that I meant ghosts? Ghosts lack shape, for future reference. Her presence will continue to be undeniable, like binding chains. Remember this, too. Fate can still be subverted, or haggled with, when it cannot be avoided altogether. As my mother used to say: if you can’t negate, negotiate.”`, 
        penance: `“Lined with stinking roses, an ouroburian cesta snarls like a seven-pointed serpent beneath your feet. If you follow it—heed my immutable caution—a series of sorrow-edged scenes will unfold before you. You will read the details of her life in annals of stained glass… Natalia: exchanging burnished bronze with rich strangers in a bustling marketplace. Natalia: crooning along with the guttural cries of alley-cats. Natalia: on a stage, her back arched, a swan nosing for seeds of grain in the dark, damp space between her thighs. Natalia: on tender knees, crouched beneath a swollen yew-stump… She liked to sing, didn’t she? Your Natalia. Recall ye the clock, which the mistress does feed, and the questing knight-beast, with his vow all sworn free. We marched to her drum with anoeth glee. Heaven’s distant gleam, still elusive to thee… That paradoxical dawn, you found a note on her pillow. Nolava is my realm, it said. The sorcery is my eye. The vengeful serpilions are my voice. Love, Natalia. You do not remember? … Has it been that long?”`, 
        image: "Entrance.jpg"
    }, 
    {
        escape: `“When the Time-Mistress buries the severed limbs of the Seven-Skulled in the Desert of Salt, you will stir awake in an alleyway next to a butcher shop. Your eyes will leak with unfamiliar faces: your memories will run together like watercolors. The stain - the damned stain - the moment which is neither past nor future but eternally, inescapably present - has returned to you. From far away. A long, treacherous distance. Your breath will race—your pulse will whirl. You will, against your will, remember that which you would slaughter on an altar to forget. But the serpilions have scented ripe prey within you, and nothing can deter their talon-beaks, their grasping hungers. If only you had kept your impulses buried! Well, you were never insulated—indoctrinated?—like we were. There are torments beyond death. Who can blame you for mistakes that you could not have known you were making? Cold and uncertain, grim as charcoal, raw as wounds. The inevitable grinding stalks the streets that neither rituals nor penance can change… but perhaps you have other options.”`, 
        penance: `“There are worlds beyond truth. Elegant and flowing, decadent as stolen gold, sharp as [quartz-sherd]. You will wake in the luxurious and unfamiliar embrace of a close friend’s old school-chum’s sister’s second husband’s estate. Your temples throb with the beat of last night’s celebration: your heart sinks like a corpse to the bottom of a lake. The spot - the damned spot - the spot which has stolen both joy and sorrow - has come to blur your vision again. Your hands will tremble as you button your coat; your steps will falter as you cross the threshold and pass back into the world. Your eyes will leak yesterday’s gin. Guilt has left its mark within you, and only death or disarticulation can erase it. This is not the answer that you seek, Лазаръ, but it is the one that you deserve: An irrefutable dark stumbles blindly through vast palaces infested by secrets and moths. It cannot be destroyed, and it cannot be evaded. When it finds you, it will offer you two endings: one of smoke, and one of fire. Do not be fooled. These are the same ending. You must traverse many pitfalls, and be wary of what you reveal to men in masks—”`,
        image: "Entrance.jpg"
    }, 
    {
        escape: `“St. Malic’s is where the guilty go to shed their sins, to partake in the Sacrament of Penance, and to steer clear of the repercussions of their wrongdoings. Mostly clear. The secrets you will learn in her hallowed booths are silver-teared and sanctified, veiled admissions of guilt delivered in agonal tones. Travel through the heart of the city, where cobblestone pathways meet shadowed spire. Scour the ancient texts for guidance. You will scarcely recognize the nave, even if you have knelt at its altar before; this particular order of priests hoards confessions like jealous dragons. Inside the booth, it is warm and dark, like a cocoon. Through the divider, you will just barely notice the priest’s eyes, which glow like burning embers. Driven to desperation, painfully aware of your predicament and its recursive nature, you will confess everything: the argument, the revelation of physical, emotional, and philosophical infidelities, the night that ended all other nights. The priest will answer you with ravaged lungs, in a voice that reminds you of rivers and serpents. A curse has found its way into your soul. You have two options: the mercy of the moths, or divine intervention. To pursue the path of the moths, you will have to mean it. Your studies will become distant memories: silly ceremonies for smaller beings, meaningless rituals, false reassurances. No, you will never return to your old life. But if you flee to a different past, you might follow in the footsteps of Orestes, who was the first of the damned to outwit his shackles. … Listen closely. I will not repeat myself. First, you must steal three secrets from the realm of the weeping stars. Second, there is a monastery—”`,
        penance: `“When the star of Mediateth seeks shelter in the Palace of the Dawn-Maiden, you will don a cloak fringed with cobwebs and dust. A secret will weight heavy in your chest: you know that the Morgen requires a tangible confession. Are you capable of giving one? Your detective will saunter towards you, his fedora cocked low, his suit-jacket tossed, deliciously casually, over his shoulder. The moonlight—in my opinion as a professional, of course; that is, my professional opinion—will greatly accentuate the subtly muscular curvature of his silhouette. But you will have to judge the aesthetics of the scene for yourself, I suppose… His figure wavers like a mirage in the serpentine dark. You will wonder how you got there—if this meeting was truly premeditated—when you even agreed to find him by the dappled banks of the Amorous Ford at witching-hour, in the first place. You hesitate, so the detective speaks first, and the detective speaks at length: about time and its tricks, cycles of growth and decay, the inevitable grinding of Mokosh’s knife against the whetstone of the world. How is it that I can travel between the veils? He asks. I didn’t learn the technique on my own. I’m not ashamed of what I did to leave that place. But we’re talking about you—remember? His grin is charm and teeth. Waves of understanding wash over you. Chronological knots, hissing and wrestling like furious, seven-faced snakes. Lingering doubts. Memories of knives and arguments in vivid grayscale. Anchors lashed to the tongues of dragons… Shadows puddle around the detective’s feet. White mist hangs like an axe over the frozen river. In this moment, to you, he will look as unwavering as stone... How long will you sit there, together, with your breath pale-white and your toes in the wintry grass? I cannot track it. Long enough that the sun has risen by the time he finishes talking. Long enough that it will feel like a long, long time. Here, the detective will murmur, before he disappears into the fog. Time behaves differently around you. Me, too. This might help. It is a pocket-watch with hands that tick neither correctly (in the direction of the future) nor backwards (in the direction of the past). Someone has painted the face to resemble a white tiger’s toothy visage, and the glass is warm to the touch.”`,
        image: "Entrance.jpg"
    }, 
    {
        escape: `“The serpilions are notoriously unforgiving, but they permit their inmates, occasionally, to wander in the forest of fantastiques, where each fruit swells with untold secrets, where the lichways writhe in endless loops, where the wind frictions the soul. In a dream, you will trample the Underfoot, and the rustle of the leaves will ripple outwards through time, the haunting echoes of the incidental creations of a glowing volve, a life erratically rewound, a scream unsilenced. Igneal-amber wrestles with velvet-mesonoxia. Here, there is neither dusk nor dawn, only epoches of twilight temporized and indesinent night. Glass-crabs mourn like banshees under the moon’s crumbling ravelin, and the stars pulsate with a ghastly radiance. Your eyes will leak dawn, but it will not sting. Here, you may glimpse her youth through roseate curtains, donning masks of rouge and despair, humming lullabies from forgotten days. Strangers pass, leaving traces of pity and disdain in their wake. Unrelenting, she pursues restless desires: sunrise, love, redemption, sanctuary. A new twilight. The cycle endures—lingers—the soft drizzle that falls when the moon hides its face. The suthers of alleyways. The shadows that tongue her eye-lack in lamplight. The soft drizzle where the moon hides. The sutures of alleyways. Shadows, dancing in lamplight. Escape surges like a thunderstorm in her chest. When she sings to the stars, alone in the woods that she knew from childhood, the melody is thick with longing. Follow the parade of shades into a fog-covered abyss; follow them down into the porous tunnels of the divine plexus. Asemia will stitch shut your mouth so that you may learn the tongue of silence. Your voice will fade: you will feel chills. Her sisters will bind the arteries of your conscience: you will know horror. Guilt will retreat to the foundational fissure of your being: the one in the crux of your belly-button, where the first innocence was lost, where the Unmade King learned the treachery of spiders and scribes…”`, 
        penance: `“The threefold function, Dr.  Bellweather explains, is to react quickly to light, to move with precision, and to focus with impeccable accuracy. And yet—one glance at this lecture hall, with its sheer abundance of spectacles, should reaffirm the eye’s many vulnerabilities! Overhead lights will cast long, eerie shadows across a shifting sea of students, hunched, scribbling, over their notes. When you leave, blinking your way back into the world, you can’t stop picturing the slide of an exposed retina. The swift adjustments from light to dark, so much like a caged bird, enigmatic and incoherent and fluttering… Now, a narrow street—a butcher-shop—the room above it. You will unlock the water-stained door, and your apartment will emerge, cluttered and empty, disheveled with dark. There will be a half-melted candle on the writing-desk in the corner of the parlor room, as there always is. You will light it with your last match, fished out of a crushed emerald matchbox, courtesy of your local pub. How often do you dream of fire? Of candlelight? There are shadows on the wall that you will beg yourself not to recognize, to no avail. One reaches for the other, as if welcoming a romantic embrace. One raises its fist.”`,
        image: "Entrance.jpg"
    }, 
  ];
  
// Counters for Escape and Penance scenes
let escapeCount = 0;
let penanceCount = 0;
let currentScene = 0;
let sceneType = 'intro';

// Define the ending scenes
const escapeEnding = "When the reading is done, you can no longer tell what is real and what is fantasy. Ludmilla is real, you believe. The silver pendant around her neck, slyly tucked between layers of chiffon and silk, is real. The sleeting of rain against the walls of the tent. Like moth-wings, Ludmilla chuckles. Or at least I’ve always thought so. She returns the detective’s watch; she refuses your meager offer of payment. Go. Now, she urges, pushing you gently back towards the world. Before she catches on. And she will catch on. Here, or elsewhere. We will face the repercussions, when she does. Through the flap of the tent, the sky is endless and dark, empty of stars. White mist has wrapped the rest of the circus in frosty silence. But there is possibility in darkness—in thunderstorms—as well as in fear. Outside, the detective waits for you in the shadow of an oak tree, his eyes as bright and clear as brass. He raises a hand. You kneel and offer him your neck."; 
const penanceEnding = "After you leave Ludmilla’s, you are uncertain what is real and what is fiction. You look back to reassure yourself that her tent is still behind you. It is. Of course it is. Still, you walk home with an invisible noose around your neck. Still, when you look down at your hands, your nails are caked with flesh and blood.  That night, you catapult awake from one nightmare into another. Three cloaked figures loom eagerly over your body. A leviathan tangle of eyes and spectral tendrils coils mindlessly in the air. The monotonous pounding of drums. Natalia, ethereal and terrifying in flowing robes of obsidian and ivory; beige, misshapen doll-creatures skittering around and up and inside of her skirts. She binds you to Euclidean’s nightmare-vision of an altar with silver chains. The cloaked figures do not help, or even offer to help. You try to point this out to them, but every word distorts into unintelligible croaking, and you observe in a detached sort of manner that your mouth tastes like blood. Natalia spreads her arms to the sky. The tentacles shiver in delight or impatience. o Morgana, the inevitable grinding, the river, the tiger, vanquished as spells, vanquished as the many-limbed sun, they sought your visions suppressed, you shall not be suppressed. The sky unfurls with a world-shattering roar. When it comes, the pain is dark and smooth, like a polished jewel.";
const escapeImage = "Ending-Escape.jpg"
const penanceImage = "Ending-Escape.jpg"

function initializeGame() {
    escapeCount = 0;
    penanceCount = 0;
    currentScene = 0;
    sceneType = 'intro';
    document.getElementById('content').innerText = introductionScene;
    document.getElementById('tarot').src = introductionImage;
    document.getElementById("nextbutton").innerText = "Next";
}
window.onload = initializeGame;

// Function to display the next scene
function nextScene() {
    if (currentScene >= scenePairs.length) {
        if (escapeCount > penanceCount) {
            document.getElementById('content').innerText = escapeEnding;
            document.getElementById('tarot').src = escapeImage;
        } else {
            document.getElementById('content').innerText = penanceEnding;
            document.getElementById('tarot').src = penanceImage;
        }
        document.getElementById("nextbutton").innerText = "Try again?";
        currentScene = -1;
        return
    }

    if (document.getElementById("nextbutton").innerText == "Try again?") {
        initializeGame();
    } else {
        // Determine if the next scene is an Escape or Penance scene (50-50 chance)
        const isNextSceneEscape = Math.random() < 0.5;
        console.log(isNextSceneEscape);

        // Get the next scene text
        console.log("current scene is: ", currentScene);
        const nextSceneText = isNextSceneEscape ? scenePairs[currentScene].escape : scenePairs[currentScene].penance;
        document.getElementById('content').innerText = nextSceneText;
        document.getElementById('tarot').src = scenePairs[currentScene].image;
        
        // Update the counters
        if (sceneType == 'escape') {
            escapeCount++;
        } else if (sceneType == 'penance') {
            penanceCount++;
        }

        // Increment the current scene
        currentScene = currentScene + 1;

        console.log("escapeCount", escapeCount);
        console.log("penanceCount", penanceCount);

        // Finally, set the current scene state based on dice roll
        sceneType = isNextSceneEscape ? 'escape' : 'penance';
    }
}
